'use client';

import React from 'react';
import { Dumbbell, Calendar, ChevronRight, Play } from 'lucide-react';
import { motion } from 'framer-motion';

interface WorkoutPlan {
  id: string;
  name: string;
  description: string;
  difficulty: string;
  goal: string;
  days_per_week: number;
}

interface WorkoutCardProps {
  plan: WorkoutPlan;
  isActive?: boolean;
  onSelect?: (id: string) => void;
}

const WorkoutCard: React.FC<WorkoutCardProps> = ({ plan, isActive, onSelect }) => {
  return (
    <motion.div
      whileHover={{ scale: 1.02 }}
      className={`relative overflow-hidden group rounded-xl p-5 border cursor-pointer transition-all duration-300 ${
        isActive 
          ? 'bg-gradient-to-br from-indigo-900/40 to-black border-indigo-500/50 shadow-[0_0_20px_rgba(99,102,241,0.15)]' 
          : 'bg-zinc-900/50 border-zinc-800 hover:border-zinc-700'
      }`}
      onClick={() => onSelect?.(plan.id)}
    >
      {/* RPG Glow Effect */}
      {isActive && (
        <div className="absolute top-0 right-0 w-32 h-32 bg-indigo-500/10 blur-[50px] -mr-16 -mt-16 rounded-full" />
      )}

      <div className="flex justify-between items-start mb-4">
        <div className="p-2.5 rounded-lg bg-indigo-500/10 text-indigo-400 group-hover:scale-110 transition-transform">
          <Dumbbell size={20} />
        </div>
        <div className="flex gap-2">
          <span className="px-2 py-0.5 rounded text-[10px] font-bold uppercase tracking-wider bg-zinc-800 text-zinc-400 border border-zinc-700">
            {plan.difficulty}
          </span>
          {isActive && (
            <span className="px-2 py-0.5 rounded text-[10px] font-bold uppercase tracking-wider bg-emerald-500/10 text-emerald-400 border border-emerald-500/20">
              Active
            </span>
          )}
        </div>
      </div>

      <h3 className="text-lg font-bold text-white mb-1 group-hover:text-indigo-300 transition-colors">
        {plan.name}
      </h3>
      <p className="text-sm text-zinc-400 line-clamp-2 mb-4 leading-relaxed">
        {plan.description || 'Custom workout plan generated by System.'}
      </p>

      <div className="flex items-center gap-4 text-xs text-zinc-500">
        <div className="flex items-center gap-1.5">
          <Calendar size={14} className="text-zinc-600" />
          <span>{plan.days_per_week} Days / Week</span>
        </div>
        <div className="flex items-center gap-1.5">
          <div className="w-1 h-1 rounded-full bg-zinc-700" />
          <span className="capitalize">{plan.goal.replace('_', ' ')}</span>
        </div>
      </div>

      <div className="mt-5 flex items-center justify-between">
        {isActive ? (
          <button className="flex items-center gap-2 px-4 py-2 rounded-lg bg-indigo-600 hover:bg-indigo-500 text-white text-sm font-bold shadow-lg shadow-indigo-900/20 transition-all">
            <Play size={14} fill="currentColor" />
            Resume Training
          </button>
        ) : (
          <div className="flex items-center gap-1 text-xs font-medium text-zinc-500 group-hover:text-zinc-300">
            View Details <ChevronRight size={14} />
          </div>
        )}
      </div>
    </motion.div>
  );
};

export default WorkoutCard;
