import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: 'class',
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        background: 'var(--bg-base)',
        surface: 'var(--bg-surface)',
        elevated: 'var(--bg-elevated)',
        input: 'var(--bg-input)',
        border: {
          DEFAULT: 'var(--border)',
          strong: 'var(--border-strong)',
        },
        foreground: {
          DEFAULT: 'var(--text-primary)',
          secondary: 'var(--text-secondary)',
          muted: 'var(--text-muted)',
        },
        accent: {
          DEFAULT: 'var(--accent-primary)',
          hover: 'var(--accent-hover)',
          glow: 'var(--accent-glow)',
        },
        green: {
          DEFAULT: 'var(--green)',
          50: '#ecfdf5',
          500: '#34D399',
        },
        blue: {
          DEFAULT: 'var(--blue)',
          50: '#eff6ff',
          500: '#60A5FA',
        },
        amber: {
          DEFAULT: 'var(--amber)',
          50: '#fffbeb',
          500: '#FBBF24',
        },
        pink: {
          DEFAULT: 'var(--pink)',
          50: '#fdf2f8',
          500: '#F472B6',
        },
        red: {
          DEFAULT: 'var(--red)',
          50: '#fef2f2',
          500: '#F87171',
        },
        orange: {
          DEFAULT: 'var(--orange)',
          500: '#FB923C',
        },
        coin: 'var(--coin-gold)',
        xp: 'var(--xp-purple)',
        
        // --- NEW MATERIAL 3 COLORS ---
        "on-secondary": "#260069",
        "on-secondary-fixed-variant": "#593ca6",
        "error": "#ff6e84",
        "primary-fixed-dim": "#9282ff",
        "on-primary-fixed-variant": "#280092",
        "surface-variant": "#25252d",
        "surface-container": "#19191f",
        "inverse-primary": "#5c48ce",
        "tertiary-fixed": "#6bffc1",
        "tertiary": "#cdffe3",
        "surface-container-lowest": "#000000",
        "surface-container-low": "#131319",
        "on-tertiary-fixed": "#004b33",
        "tertiary-container": "#6bffc1",
        "secondary": "#a88cfb",
        "primary": "#aea2ff",
        // "background": "#0e0e13", // using existing var instead
        // "surface": "#0e0e13", // using existing var instead
        "on-secondary-container": "#d7c8ff",
        "secondary-fixed": "#d8caff",
        "on-tertiary-fixed-variant": "#006b4a",
        "surface-container-highest": "#25252d",
        "tertiary-fixed-dim": "#5af0b4",
        "tertiary-dim": "#5af0b4",
        "on-surface": "#f9f5fd",
        "outline": "#76747b",
        "inverse-surface": "#fcf8ff",
        "primary-fixed": "#a092ff",
        "surface-tint": "#aea2ff",
        "on-primary-container": "#1f0078",
        "secondary-fixed-dim": "#ccbaff",
        "secondary-container": "#4f319c",
        "on-background": "#f9f5fd",
        "surface-container-high": "#1f1f26",
        "on-tertiary-container": "#006042",
        "surface-dim": "#0e0e13",
        "on-primary": "#2a0098",
        "inverse-on-surface": "#55545b",
        "error-container": "#a70138",
        "primary-dim": "#9d8fff",
        "on-secondary-fixed": "#3c1989",
        "error-dim": "#d73357",
        "secondary-dim": "#a88cfb",
        "surface-bright": "#2c2b33",
        "on-primary-fixed": "#000000",
        "primary-container": "#a092ff",
        "on-error-container": "#ffb2b9",
        "on-surface-variant": "#acaab1",
        "on-error": "#490013",
        "on-tertiary": "#006948",
        "outline-variant": "#48474d",
      },
      fontFamily: {
        sans: ['Inter', '-apple-system', 'BlinkMacSystemFont', 'sans-serif'],
        display: ['Plus Jakarta Sans', 'Inter', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
        headline: ['Plus Jakarta Sans', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      fontSize: {
        xs: ['0.75rem', { lineHeight: '1rem' }],
        sm: ['0.875rem', { lineHeight: '1.25rem' }],
        base: ['1rem', { lineHeight: '1.5rem' }],
        lg: ['1.125rem', { lineHeight: '1.75rem' }],
        xl: ['1.25rem', { lineHeight: '1.75rem' }],
        '2xl': ['1.5rem', { lineHeight: '2rem' }],
        '3xl': ['1.875rem', { lineHeight: '2.25rem' }],
        '4xl': ['2.25rem', { lineHeight: '2.5rem' }],
      },
      borderRadius: {
        sm: '6px',
        md: '10px',
        lg: '16px',
        xl: '24px',
      },
      boxShadow: {
        sm: 'var(--shadow-sm)',
        md: 'var(--shadow-md)',
        glow: 'var(--shadow-glow)',
      },
      keyframes: {
        'fade-up': {
          '0%': { opacity: '0', transform: 'translateY(10px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'fade-in': {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        'scale-in': {
          '0%': { opacity: '0', transform: 'scale(0.95)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        'slide-right': {
          '0%': { opacity: '0', transform: 'translateX(20px)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
        'xp-fill': {
          '0%': { width: '0%' },
          '100%': { width: 'var(--xp-width)' },
        },
        'coin-bounce': {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-8px)' },
        },
        'pulse-glow': {
          '0%, 100%': { boxShadow: '0 0 5px var(--accent-glow)' },
          '50%': { boxShadow: '0 0 20px var(--accent-glow)' },
        },
        'float-up': {
          '0%': { opacity: '1', transform: 'translateY(0)' },
          '100%': { opacity: '0', transform: 'translateY(-30px)' },
        },
        'flame': {
          '0%, 100%': { transform: 'scaleY(1) scaleX(1)' },
          '25%': { transform: 'scaleY(1.1) scaleX(0.9)' },
          '50%': { transform: 'scaleY(0.95) scaleX(1.05)' },
          '75%': { transform: 'scaleY(1.05) scaleX(0.95)' },
        },
        'typing-dot': {
          '0%, 60%, 100%': { opacity: '0.3', transform: 'translateY(0)' },
          '30%': { opacity: '1', transform: 'translateY(-4px)' },
        },
      },
      animation: {
        'fade-up': 'fade-up 250ms cubic-bezier(0.4, 0, 0.2, 1)',
        'fade-in': 'fade-in 200ms ease',
        'scale-in': 'scale-in 200ms cubic-bezier(0.4, 0, 0.2, 1)',
        'slide-right': 'slide-right 300ms cubic-bezier(0.4, 0, 0.2, 1)',
        'xp-fill': 'xp-fill 600ms cubic-bezier(0.4, 0, 0.2, 1) forwards',
        'coin-bounce': 'coin-bounce 400ms ease-in-out',
        'pulse-glow': 'pulse-glow 2s ease-in-out infinite',
        'float-up': 'float-up 600ms ease-out forwards',
        'flame': 'flame 1.5s ease-in-out infinite',
        'typing-dot': 'typing-dot 1.4s ease-in-out infinite',
      },
      spacing: {
        'sidebar': '240px',
        'topbar': '60px',
        'topbar-mobile': '56px',
        'bottomnav': '64px',
      },
    },
  },
  plugins: [],
}

export default config
